### PR TITLE
Adding DBN JSON spec

### PR DESCRIPTION
**Pull request by adarshp**
This PR adds the DBN-JSON spec for program analysis output to the Sphinx documentation in the form of a reStructuredText file.

### CODE REVIEW

**Comment by adarshp** [comment]
@cl4yton @pauldhein @pratikbhd @skdebray 

I've added the DBN-JSON spec to the Delphi documentation - please take a look at it and see if it seems good to you.

@cl4yton :

- I took out some of the notes that I thought were unnecessary, but kept some in (marked by NOTE and TODO) - could you take a look at them and see if you still want them in the document?
- The Function Decision Specification section seems incomplete - should I remove it? Or perhaps either you/ @pauldhein /@pratikbhd could fill it out?
- The code examples in the Function Container Specification seem like Python code snippets, but there are some things I don't recognize (like the Integer specification, or the <- arrow) - are they meant to be Python? Or just generic pseudocode?

**Comment by adarshp** [comment]
To build the docs, you can do

```bash
cd docs
make html
open _build/html/dbn_json_spec.html
```

If you're using Pipenv to manage your dependencies and virtual environment, you can replace the second line above with

```bash
pipenv run make html
```

**Comment by pauldhein** [comment]
Found what seems to be a bug. Looks like clicking on the API dropdown makes the DBN dropdown disappear. Is this just a side-effect of sphinx running on my local machine or is that an actual bug?

screen recording 2018-11-14 at 4 15 31 pm

**Comment by adarshp** [comment]
That's related to the ReadTheDocs Sphinx theme - see https://dynet.readthedocs.io/en/latest/index.html for another example.

**Comment by adarshp** [comment]
I'm merging this since we are getting close to the deadline and we are trying to get a PDF export from Sphinx. @pratikbhd you can still push to this branch - I am not going to delete it just yet.

**Pull request merged**
