### PR TITLE
GrFN class, round 2

### PR DESCRIPTION
**Pull request by adarshp**
Ok, I think these changes are ready to be merged into master.

This PR is a continuation of #217 . In addition to the changes there, it also implements the following:

- Reorganization of the directories - there is now an apps directory under Delphi, with `CodeExplorer` and `rest_api` (formerly `icm_api`) residing in it.
- Reorganization of test data directories
- tests have been added for the wiring of the PETPT GrFN and CAG, to prevent regression bugs.

@pauldhein - I've made the following changes that you'll probably want to review.
- I've switched from using the enum to a string comparison, mainly for readability reasons, but can revert if necessary.
- I refactored the `from_dict` method of the `GroundedFunctionNetwork` class to be a bit cleaner
- I've modified the `run` method of the `GroundedFunctionNetwork` - no need to generate a sorted list of inputs anymore - Python's dict unpacking ensures that the appropriate values get passed to the right arguments.
- I've done away with the `build_call_graph` and `build_function_sets` methods in the `ForwardInfluenceBlanket` class since they seemed to be the same as the corresponding methods in `GroundedFunctionNetwork`
- I changed the `lambda` key to `lambda_fn` to avoid conflict with the Python builtin `lambda` keyword.
- I've removed `scopes.py`

### CODE REVIEW

**Comment by adarshp** [comment]
@pauldhein - if you are ok with these changes, please squash and merge them.

**Comment by adarshp** [comment]
Closes #217 .

**Comment by cl4yton** [comment]
This is a lot of work, guys, many thanks!

**Comment by adarshp** [comment]
This PR now also closes #164 .

**Comment by adarshp** [comment]
Closed by #229

**Pull request closed without merging**
