### PR TITLE
Arrays

### PR DESCRIPTION
**Pull request by hlim1**
Modified test program analysis test for the code coverage test.
If the Travis build fails, I will undo the pull request and fix the file again.

### CODE REVIEW

**Comment by adarshp** [comment]
No need to undo the pull request - you can just push to the same branch.

**Comment by skdebray** [comment]
@adarshp What do I do to run the travis checks again?

**Comment by adarshp** [comment]
> @adarshp What do I do to run the travis checks again?

@skdebray If you push a new commit to the branch that the PR is submitted for, the Travis test runs automatically. Otherwise, when you go to a particular build in the Travis web interface, there is a button labeled 'Restart build' that you can use to run it again.

**Comment by adarshp** [comment]
@hlim1 I pushed a fix for the Travis tests - please review and let's discuss when we meet tomorrow.
@skdebray - this looks good to me to merge, when you get a chance, could you review and then do a squash and merge?

**Comment by skdebray** [comment]
In the interests of time, I'll go ahead and merge.  But we really need to revisit this code, refactor, and add comments.  Let's do that once the April milestone is past and we don't have a deadline staring us in the face.

**Comment by hlim1** [comment]
@adarshp Thanks for fixing the tests. For the further details of the Travis test, yes, we'll discuss tomorrow.
@skdebray I agree. We should visit again later after the milestone to restructure and add more details to the code.

Thanks!

**Pull request merged**
