### PR TITLE
Changing import path so it works on Jons server

### PR DESCRIPTION
**Pull request by adarshp**
@stephensj2 I changed it to `from .genCode import *` - does that work for you? If so, please merge this commit as well.

### CODE REVIEW

**Comment by stephensj2** [comment]
It still doesn't like it. Here's the error I get now:

Traceback (most recent call last):
  File "scripts/genPGM.py", line 11, in <module>
    from .genCode import *
ModuleNotFoundError: No module named '__main__.genCode'; '__main__' is not a package

**Comment by adarshp** [comment]
@stephensj2 I reverted the last commit - do you have the delphi source directory in your $PYTHONPATH?

**Comment by stephensj2** [comment]
I do not.

**Comment by adarshp** [comment]
Can you add it and see if having 

`from delphi.program_analysis.autoTranslate.scripts.genCode import *` works?

On my computer, I have the following line in my `~/.bash_profile`: 

```bash
export PYTHONPATH=~/ml4ai/delphi/:$PYTHONPATH
```

**Comment by stephensj2** [comment]
Yeah, that works.

**Pull request merged**
