### PR TITLE
Fix Pipenv integration with Travis CI

### PR DESCRIPTION
**Pull request by adarshp**
This PR fixes up Pipenv integration with Travis CI that arise due to NetworkX version mismatches between INDRA and Delphi.

### CODE REVIEW

**Comment by cl4yton** [comment]
Have you heard from INDRA folks about when they might complete upgrading NetworkX?

**Comment by cl4yton** [comment]
Thanks @bgyori !

**Comment by adarshp** [comment]
Yeah, for now the way to go is to do `pipenv install -d` followed by `pipenv install networkx==2.1` which overrides NetworkX 1.11 which is installed as a dependency of INDRA.

**Comment by cl4yton** [comment]
Go it.  Should we update the <delphi_root>/README.md?  It currently says to do just `pipenv install -d --ignore-pipfile`.  I can replace with the above two step if you concur.

**Comment by adarshp** [comment]
Yes, thank you!

**Pull request merged**
