### PR TITLE
Sensitivity analysis code + for2py librarification

### PR DESCRIPTION
**Pull request by adarshp**
Sensitivity Analysis + for2py 'librarification'
===============================

This PR adds functionality for performing sensitivity analyses using models extracted from Fortran code, refactors `for2py` to move it to being more of a library than a collection of scripts, and implements other miscellaneous improvements.

for2py changes
----------------
- `delphi/translators/for2py/f2grfn.py`: 
  - `f2grfn.py` has been refactored to write fewer intermediate files to disk, cleaning up certain files automatically with the `save_intermediate_files` switch.
  - At a high level, the code is now more 'librarified' - there are no arguments to specify whether the functions are being called by a test module or networks.py etc. There is no 'main' method anymore - instead, equivalent functionality (I hope) has been moved to a standalone script named `scripts/f2grfn_standalone.py`
- `preprocessor.py`:
  - The following functions in `preprocessor.py` has been renamed to describe their functionality more explicitly:
    - `preprocess_file` --> `get_preprocessed_lines_from_file`
    - `preprocess` --> `preprocess_lines`
  - The `process` function in `preprocessor.py` has been removed since it is not needed anymore.
  - The `create_preprocessed_file` function has been added.
- The function `create_python_source_list` in `pyTranslate.py` has been renamed to `get_python_sources_and_variable_map` to better reflect the return type.
- `rectify.py`: The class `RectifyOFPXML` has been renamed to `RectifiedXMLGenerator` to more closely align with the names of other classes in `for2py`.
- `translate.py`: The function `xml_to_py` no longer needs the second argument (the input fortran filename) - the functionality to get comments has been extracted to a separate location in `f2grfn.py`.
- `delphi/translators/for2py/autoTranslate` has been deleted since it is outdated.
- Docstrings of some modules have been changed to reflect that they are part of a library rather than standalone scripts.
- Dates have been removed from the docstring of mod_index_generator since it's hard to keep the 'last updated' date updated manually and probably easier to just let the git commit history keep track of that.

Miscellaneous changes
-----------------------
- Most files have been run through the Black code auto formatter (with line width 79), and through the autoflake tool to remove unused imports. 
- Type information has been added to some function signatures.
- Some typos have been fixed in docstrings.
- The function `output_link_graph` in `delphi/GrFN/linking.py` now takes an additional option to specify the output filename.
- Some cleanup code has been sprinkled throughout the library and test code so that running the test suite produces fewer files to clean up.
- Removed some stray print statements.
- Removed some outdated tests in `scripts/khan/tests`
- Set the minimum required version of `seaborn` to 0.10.0 to work with numpy version 0.18.0 (https://github.com/mwaskom/seaborn/issues/1907)
- Other minor improvements, fixes, etc.

This PR supersedes and closes #441 .

### CODE REVIEW

**Comment by adarshp** [comment]
@skdebray @hlim1 @pauldhein @skhan1020 @pratikbhd I took a stab at 'librarifying' for2py - please take a look at the change summary and let me know if there is anything you'd like me to modify - in particular, if there was code you wrote that I changed in a way that doesn't work for you, let me know.

**Comment by skdebray** [comment]
@adarshp Looks good!  Thanks for doing this. :)

**Comment by adarshp** [comment]
> @adarshp why are we merging this branch into master as opposed to merging it into `aske-khan`?

1. So that there could be a more detailed top-level description, and
2. I thought it would be quicker :)

> Also can we avoid adding so many scripts all at once? I think that the large number of scripts under `scripts/khan/Ibex/` should be added in a separate PR (if at all).

Agree -  I've removed them from this branch. 

I was originally thinking that scripts/ could be like a sandbox for Delphi devs, but thinking about it a bit more, git branches are better sandboxes.

@skhan1020 they will still be in the aske-khan branch if you need them in the future.

> Other than that, this all looks good to me!

**Comment by hlim1** [comment]
@adarshp Thank you for librifying `f2grfn`. I've looked through the changes and ran `scripts/f2grfn_standalone.py`. Everything looks good and passes all `test_program_analysis` tests. However, one thing I noticed is that the change removing `test_call` indicator arguments,`f2grfn_standalone.py` can't handle generated files on completion of the program. For example, `_lambdas.py` and `_GrFN.json` files are left in the directory as expected for MA, but also the rectified XML file remains as well, but not needed for MA, I guess. Moreover, other files such as preprocessed fortran file, original XML file, pickle file, and Python IR files are removed, which are necessary files for us (PA team). For now, these changes are good and I can make an update to the. code. If this branch needs to be merged into the master, please do so. I. will create another branch and work on from it.  Thanks!

**Comment by adarshp** [comment]
@hlim1 I've pushed a couple of commits that should fix this issue - now running f2grfn_standalone.py will keep all the intermediate files, including the preprocessed fortran file, original XML, rectified XML, translated Python, GrFN.json, and *_lambdas.py files.

To remove any of these, look for the variable `save_intermediate_files` in `f2grfn.py` and add `os.remove` lines as necessary.

Just to clarify, for MA, we don't need the intermediate `*_GrFN.json` file.

I mean `f2grfn_standalone.py` to be solely for the purpose of the PA team to ease their development process - the rectified XML is automatically deleted when for2py is invoked by `networks.py` or the test suite.

**Pull request merged**
