### PR TITLE
Added classpath for OFP

### PR DESCRIPTION
**Pull request by pratikbhd**
Fix for issue #167 which could not execute the OFP. Added an instantiation to CLASSPATH to handle this but I think the CLASSPATH should be assigned on some other file instead of `test_program_analysis.py`.

### CODE REVIEW

**Comment by skdebray** [comment]
I wonder whether the problem may be due to a newer version of `OpenFortranParser` that I think was installed recently?  I just pulled the latest version of the master branch and now get an error when I try to run `OpenFortranParser`:

```
$ java fortran.ofp.FrontEnd --class fortran.ofp.XMLPrinter --verbosity 0 test01.f
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/antlr/runtime/TokenStream
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.antlr.runtime.TokenStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

**Comment by skdebray** [comment]
@pratikbhd Can you post here the CLASSPATH (and maybe the OFP-relevant jar files) you used?  Maybe I can plagiarize from you. :)

**Comment by pratikbhd** [comment]
@skdebray The CLASSPATH I added on test_program_analysis is the following:
`os.environ["CLASSPATH"] = (str(Path(__file__).parent / "../" / "delphi" / "translators" / "for2py" / "bin" / "*"))`

Also attached are the OFP related jar files that I am currently using.
[OFP jars.zip](https://github.com/ml4ai/delphi/files/2833370/OFP.jars.zip)

**Comment by skdebray** [comment]
That's weird.  I have the same jar files as what you posted, and my CLASSPATH points to them.  But I get an error when I run OpenFortranParser.  The error message mentions 
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/antlr/runtime/TokenStream
```
I don't know what the issue may be.

**Comment by skdebray** [comment]
@pratikbhd I'm pretty certain the problem has to do with the new `OpenFortranParser` jar files.  I switched to the `arrays` branch (which uses the old jar files) and am able to run the parser without any problems.

Did the site that had the new OpenFortranParser files come with a different `antlr` jar file?

**Pull request merged**
