### PR TITLE
Merging program analysis development work into master

### PR DESCRIPTION
**Pull request by adarshp**
It's not perfect, but I think it's time to kill this branch.

### CODE REVIEW

**Comment by cl4yton** [comment]
It appears that Travis is failing -- but then I see that the branch is reported as having no conflicts.  Other than that, I recommend doing the merge!

**Comment by cl4yton** [comment]
(I mistakenly hit close and comment when I just meant comment)

**Comment by adarshp** [comment]
Some dependency resolution issues with tangent - I took it out of the Pipfile for now, let's see if it passes.

**Comment by adarshp** [comment]
Travis passed, so I merged it.

**Pull request merged**
