### PR TITLE
Preprocessor to lower

### PR DESCRIPTION
**Pull request by skdebray**
This PR has the preprocessor convert the Fortran source code into lower-case before writing it out.  This frees us from having to constantly convert to lower-case in translate.py and pyTranslate.py.

### CODE REVIEW

**Comment by skdebray** [comment]
@adarshp It looks like the  checks are failing on this PR with the following error:
```
self = <delphi.translators.for2py.pyTranslate.PythonCodeGenerator object at 0x2b96e8a7a3c8>
node = {'name': 'MSALB', 'tag': 'arg', 'type': 'REAL'}
printState = <delphi.translators.for2py.pyTranslate.PrintState object at 0x2b96e8a8a390>
    def printArg(self, node, printState: PrintState):
        try:
>           var_type = TYPE_MAP[node["type"]]
E           KeyError: 'REAL'
delphi/translators/for2py/pyTranslate.py:533: KeyError
```

I looked at the preprocessed Fortran source output by the preprocessor, as well as the xml files obtained from it, and they are all in lower-case so I don't see where the upper-case string "REAL" could be coming from.  It so happens that the source file `delphi/tests/data/program_analysis/PETPT.for` (which is the test that failed) has it in upper case, but the preprocessor should have converted everything to lower case anyway.  Any thoughts?

**Comment by adarshp** [comment]
The function that is used for integration with the rest of Delphi is `preprocessor.process`: 

https://github.com/ml4ai/delphi/blob/be8536c9706411ec8745b62f888be55dd4a29281/delphi/translators/for2py/preprocessor.py#L313-L324

However, the lowering happens outside of that function, in the `main` block:

https://github.com/ml4ai/delphi/blob/be8536c9706411ec8745b62f888be55dd4a29281/delphi/translators/for2py/preprocessor.py#L344

So the lowercasing never actually happens unless preprocessor.py is invoked as a script....

**Comment by adarshp** [comment]
i.e. to fix it, you would need to move the lowercasing functionality inside the `process` function (and in general, for integration, it's best to keep as much of the logic within functions and outside of the main block!)

**Comment by skdebray** [comment]
Ah, I get it.  Thank you. :+1:

**Pull request closed without merging**
